---
abstract: 'A container for functions of the ClusterSSH programs'
author:
  - 'Duncan Ferguson <duncan_j_ferguson@yahoo.co.uk>'
build_requires:
  CPAN::Changes: '0.27'
  File::Slurp: '0'
  File::Temp: '0'
  File::Which: '0'
  Perl::Tidy: '20180220'
  Readonly: '0'
  Test::Differences: '0'
  Test::DistManifest: '0'
  Test::PerlTidy: '0'
  Test::Pod: '0'
  Test::Pod::Coverage: '0'
  Test::Trap: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-ClusterSSH
provides:
  App::ClusterSSH:
    file: lib/App/ClusterSSH.pm
    version: 4.14_01
  App::ClusterSSH::Base:
    file: lib/App/ClusterSSH/Base.pm
    version: '0.02'
  App::ClusterSSH::Cluster:
    file: lib/App/ClusterSSH/Cluster.pm
    version: '0.01'
  App::ClusterSSH::Config:
    file: lib/App/ClusterSSH/Config.pm
    version: '0.02'
  App::ClusterSSH::Getopt:
    file: lib/App/ClusterSSH/Getopt.pm
    version: '0.01'
  App::ClusterSSH::Helper:
    file: lib/App/ClusterSSH/Helper.pm
    version: '0.02'
  App::ClusterSSH::Host:
    file: lib/App/ClusterSSH/Host.pm
    version: '0.03'
  App::ClusterSSH::L10N:
    file: lib/App/ClusterSSH/L10N.pm
  App::ClusterSSH::L10N::en:
    file: lib/App/ClusterSSH/L10N/en.pm
  App::ClusterSSH::Range:
    file: lib/App/ClusterSSH/Range.pm
  App::ClusterSSH::Window:
    file: lib/App/ClusterSSH/Window.pm
    version: '0.01'
  App::ClusterSSH::Window::Tk:
    file: lib/App/ClusterSSH/Window/Tk.pm
    version: '0.01'
recommends:
  Sort::Naturally: '0'
requires:
  Exception::Class: '1.31'
  File::Glob: '0'
  File::Path: '0'
  Getopt::Long: '0'
  Locale::Maketext: '0'
  Tk: '800.022'
  Try::Tiny: '0'
  X11::Protocol: '0.56'
  X11::Protocol::WM: '0'
  perl: v5.8.4
  version: '0.77'
resources:
  Coverage: https://coveralls.io/github/duncs/clusterssh
  Repository:
    - http://github.com/duncs/clusterssh
  bugtracker: https://github.com/duncs/clusterssh/issues
  homepage: http://github.com/duncs/clusterssh/wiki
  license: http://dev.perl.org/licenses/
version: 4.14_01
x_serialization_backend: 'CPAN::Meta::YAML version 0.016'
